name: Tests

on: push

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    env: 
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}  


    strategy:
      matrix:
        os: [ubuntu-latest]
        

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Python ✨
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest

      - name: Send GitHub Action trigger data to Slack workflow
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: 'CICD ongoing...'
          steps: ${{ toJson(steps) }}
          channel: '#tpcicd'
        if: always()

      - name: Analysing the code with pylint
        run: |
          pip install pylint
          pylint $(git ls-files '*.py')