name: Tests

on: push

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Python ✨
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest

     - name: Python Checkstyle
        timeout-minutes: 10
        run: |

          pylint 

    - name: Send GitHub Action trigger data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}